//! Golden vectors for the core-PostGIS 3D metric family.
//!
//! `tests/golden/threed.jsonl` is generated by `scripts/golden/threed.sql`
//! against the same reference image every other suite uses. Only the nine
//! functions core PostGIS has *without* SFCGAL are covered, because the
//! solid-modelling family is not in that image at all — there is nothing to
//! generate vectors from, which is the reason kenro does not implement it
//! (`tmp/3d-predicates.md`).
//!
//! The operands arrive as WKT with a Z, which kenro's `ST_GeomFromText`
//! refuses by design. So the harness builds the blob itself: it parses the WKT
//! here and emits ISO WKB, which is how a 3D geometry reaches kenro in practice
//! anyway (written by GDAL, QGIS or a CityGML importer).

mod common;

use kenro::functions::threed_metric as m3;

/// Parse the small WKT-with-Z dialect the vectors use into ISO WKB.
///
/// Deliberately narrow: exactly the types `scripts/golden/threed.sql` writes.
/// A general WKT parser is `ST_GeomFromText`'s job, and it refuses Z on purpose.
mod wkt_z {
    /// `POINT Z (…)`, `LINESTRING Z (…)`, `POLYGON Z ((…))`, the MULTI\* forms,
    /// `POLYHEDRALSURFACE Z(…)`, `TIN Z(…)`, `TRIANGLE Z(…)`, and `… EMPTY`.
    pub fn to_wkb(wkt: &str) -> Option<Vec<u8>> {
        let wkt = wkt.trim();
        let upper = wkt.to_ascii_uppercase();
        let head = upper.split(['(', ' ']).next().unwrap_or("");
        if upper.ends_with("EMPTY") {
            // An empty geometry of the named type: count 0, no coordinates.
            let base = match head {
                "POINT" => return None, // no vector uses POINT EMPTY
                "LINESTRING" => 2u32,
                "POLYGON" => 3,
                _ => return None,
            };
            let mut v = vec![0x01u8];
            v.extend_from_slice(&(1000 + base).to_le_bytes());
            v.extend_from_slice(&0u32.to_le_bytes());
            return Some(v);
        }
        // The coordinate text is everything from the first '(' to the last ')'.
        let body = &wkt[wkt.find('(')?..=wkt.rfind(')')?];
        match head {
            "POINT" => Some(point(nums(body)?)),
            "LINESTRING" => Some(run(2, &coords(body)?)),
            "POLYGON" => Some(rings(3, body)?),
            "TRIANGLE" => Some(rings(17, body)?),
            "MULTIPOINT" => {
                let parts = split_parts(&body[1..body.len() - 1])?;
                let mut v = header(4, parts.len());
                for p in parts {
                    v.extend_from_slice(&point(nums(&p)?));
                }
                Some(v)
            }
            "MULTILINESTRING" => {
                let parts = split_parts(&body[1..body.len() - 1])?;
                let mut v = header(5, parts.len());
                for p in parts {
                    v.extend_from_slice(&run(2, &coords(&p)?));
                }
                Some(v)
            }
            "MULTIPOLYGON" => {
                let parts = split_parts(&body[1..body.len() - 1])?;
                let mut v = header(6, parts.len());
                for p in parts {
                    v.extend_from_slice(&rings(3, &p)?);
                }
                Some(v)
            }
            "POLYHEDRALSURFACE" | "TIN" => {
                let base = if head == "TIN" { 16 } else { 15 };
                let patch = if head == "TIN" { 17 } else { 3 };
                let parts = split_parts(&body[1..body.len() - 1])?;
                let mut v = header(base, parts.len());
                for p in parts {
                    v.extend_from_slice(&rings(patch, &p)?);
                }
                Some(v)
            }
            _ => None,
        }
    }

    fn header(base: u32, count: usize) -> Vec<u8> {
        let mut v = vec![0x01u8];
        v.extend_from_slice(&(1000 + base).to_le_bytes());
        v.extend_from_slice(&(count as u32).to_le_bytes());
        v
    }

    fn point(c: [f64; 3]) -> Vec<u8> {
        let mut v = vec![0x01u8];
        v.extend_from_slice(&1001u32.to_le_bytes());
        for o in c {
            v.extend_from_slice(&o.to_le_bytes());
        }
        v
    }

    fn run(base: u32, cs: &[[f64; 3]]) -> Vec<u8> {
        let mut v = header(base, cs.len());
        for c in cs {
            for o in c {
                v.extend_from_slice(&o.to_le_bytes());
            }
        }
        v
    }

    fn rings(base: u32, body: &str) -> Option<Vec<u8>> {
        let parts = split_parts(&body[1..body.len() - 1])?;
        let mut v = header(base, parts.len());
        for p in parts {
            let cs = coords(&p)?;
            v.extend_from_slice(&(cs.len() as u32).to_le_bytes());
            for c in cs {
                for o in c {
                    v.extend_from_slice(&o.to_le_bytes());
                }
            }
        }
        Some(v)
    }

    /// Split `(a)(,)(b)` style sibling groups at depth 0.
    fn split_parts(inner: &str) -> Option<Vec<String>> {
        let mut out = Vec::new();
        let mut depth = 0i32;
        let mut start = None;
        for (i, ch) in inner.char_indices() {
            match ch {
                '(' => {
                    if depth == 0 {
                        start = Some(i);
                    }
                    depth += 1;
                }
                ')' => {
                    depth -= 1;
                    if depth == 0 {
                        out.push(inner[start?..=i].to_string());
                    }
                }
                _ => {}
            }
        }
        if out.is_empty() {
            // A flat list: `1 2 3,4 5 6`, as MULTIPOINT sometimes writes.
            out = inner
                .split(',')
                .map(|s| format!("({})", s.trim()))
                .collect();
        }
        Some(out)
    }

    fn coords(body: &str) -> Option<Vec<[f64; 3]>> {
        let inner = body.trim().trim_start_matches('(').trim_end_matches(')');
        inner.split(',').map(nums_str).collect()
    }

    fn nums(body: &str) -> Option<[f64; 3]> {
        nums_str(body.trim().trim_start_matches('(').trim_end_matches(')'))
    }

    fn nums_str(s: &str) -> Option<[f64; 3]> {
        let mut it = s.split_whitespace().map(|n| n.parse::<f64>());
        Some([
            it.next()?.ok()?,
            it.next()?.ok()?,
            it.next().transpose().ok()?.unwrap_or(0.0),
        ])
    }
}

/// The ordinates of a 3D blob kenro produced, in order.
fn ordinates(blob: &[u8]) -> Vec<[f64; 3]> {
    let mut out = Vec::new();
    kenro::coords::for_each_coord(blob, &mut |c| out.push([c.x, c.y, c.z.unwrap_or(0.0)])).unwrap();
    out
}

/// PostGIS's `ST_AsEWKT` output, parsed back to ordinates for comparison.
fn expected_ordinates(ewkt: &str) -> Vec<[f64; 3]> {
    let wkb = wkt_z::to_wkb(
        &ewkt
            .replace("POINT(", "POINT Z (")
            .replace("LINESTRING(", "LINESTRING Z ("),
    )
    .unwrap_or_else(|| panic!("cannot parse expected {ewkt}"));
    ordinates(&wkb)
}

fn close(a: f64, b: f64) -> bool {
    (a - b).abs() <= 1e-9 * a.abs().max(b.abs()).max(1.0)
}

#[test]
fn golden_threed_metrics() {
    let mut checked = 0usize;
    for v in common::load("threed") {
        let a = wkt_z::to_wkb(v.a.as_deref().unwrap())
            .unwrap_or_else(|| panic!("{}: cannot build operand a", v.id));
        let b =
            v.b.as_deref()
                .map(|w| wkt_z::to_wkb(w).unwrap_or_else(|| panic!("{}: operand b", v.id)));
        // `effective()` prefers a documented-divergence override; `kenro_null`
        // is the one that cannot be spelled as a value (see common/mod.rs).
        let expected = v.effective();
        let want_null = v.kenro_null.unwrap_or(false);
        match v.func.as_str() {
            "3ddistance" | "3dmaxdistance" => {
                let got = if v.func == "3ddistance" {
                    m3::st_3d_distance(&a, b.as_ref().unwrap()).unwrap()
                } else {
                    m3::st_3d_max_distance(&a, b.as_ref().unwrap()).unwrap()
                };
                match expected.as_f64() {
                    Some(want) => {
                        let got = got.unwrap_or_else(|| panic!("{}: got NULL", v.id));
                        assert!(close(got, want), "{}: got {got}, want {want}", v.id);
                    }
                    None => assert!(expected.is_null() && got.is_none(), "{}: {got:?}", v.id),
                }
            }
            "3dintersects" => {
                let got = m3::st_3d_intersects(&a, b.as_ref().unwrap()).unwrap();
                assert_eq!(Some(got), expected.as_bool(), "{}", v.id);
            }
            "3ddwithin" | "3ddfullywithin" => {
                let d = v.arg.unwrap();
                let got = if v.func == "3ddwithin" {
                    m3::st_3d_dwithin(&a, b.as_ref().unwrap(), d).unwrap()
                } else {
                    m3::st_3d_dfully_within(&a, b.as_ref().unwrap(), d).unwrap()
                };
                assert_eq!(Some(got), expected.as_bool(), "{}", v.id);
            }
            "3dclosestpoint" | "3dshortestline" | "3dlongestline" => {
                let got = match v.func.as_str() {
                    "3dclosestpoint" => m3::st_3d_closest_point(&a, b.as_ref().unwrap()),
                    "3dshortestline" => m3::st_3d_shortest_line(&a, b.as_ref().unwrap()),
                    _ => m3::st_3d_longest_line(&a, b.as_ref().unwrap()),
                }
                .unwrap();
                if want_null {
                    assert!(got.is_none(), "{}: expected NULL, got a geometry", v.id);
                    checked += 1;
                    continue;
                }
                match expected.as_str() {
                    None => assert!(expected.is_null() && got.is_none(), "{}", v.id),
                    Some(want) => {
                        let got = got.unwrap_or_else(|| panic!("{}: got NULL", v.id));
                        let (g, w) = (ordinates(&got), expected_ordinates(want));
                        assert_eq!(g.len(), w.len(), "{}: {g:?} vs {w:?}", v.id);
                        for (gc, wc) in g.iter().zip(&w) {
                            for k in 0..3 {
                                assert!(close(gc[k], wc[k]), "{}: {g:?} vs {w:?}", v.id);
                            }
                        }
                    }
                }
            }
            "3dlineinterpolatepoint" => {
                let got = m3::st_3d_line_interpolate_point(&a, v.arg.unwrap()).unwrap();
                let (g, w) = (
                    ordinates(&got),
                    expected_ordinates(expected.as_str().unwrap()),
                );
                for (gc, wc) in g.iter().zip(&w) {
                    for k in 0..3 {
                        assert!(close(gc[k], wc[k]), "{}: {g:?} vs {w:?}", v.id);
                    }
                }
            }
            other => panic!("unknown fn {other} in the threed suite"),
        }
        checked += 1;
    }
    assert!(checked > 150, "only {checked} vectors ran");
}
