//! Golden vectors for the box accessors' TEXT argument.
//!
//! `tests/golden/box_text.jsonl` is generated by `scripts/golden/box_text.sql`
//! against the reference PostGIS. The vectors feed a `BOX3D(…)` string
//! straight into `ST_XMin` and friends, which is how PostGIS's only overload
//! for those six — `box3d`, reached through `box3d_in` — is exercised without
//! a geometry in sight. kenro takes the same union of BLOB and box text
//! because SQLite has neither a `box3d` type nor the implicit cast a geometry
//! travels through to reach one.
//!
//! Rows carrying `kenro_expected` are the measured deviations, in both
//! directions: kenro accepts spellings PostGIS's case-sensitive, unanchored
//! `sscanf` parser refuses (`BOX(…)`, lower case, leading whitespace), and
//! refuses the strings that same parser accepts by accident (a junk tail, a
//! missing close paren, mismatched corner dimensions). `src/functions/box3d.rs`
//! carries the table and the reasoning.

mod common;

use kenro::functions::{rtree, threed};

fn call(f: &str, arg: &[u8]) -> kenro::error::Result<Option<f64>> {
    match f {
        "xmin" => rtree::st_min_x(arg),
        "xmax" => rtree::st_max_x(arg),
        "ymin" => rtree::st_min_y(arg),
        "ymax" => rtree::st_max_y(arg),
        "zmin" => threed::st_zmin(arg),
        "zmax" => threed::st_zmax(arg),
        other => panic!("unknown fn {other} in the box_text suite"),
    }
}

#[test]
fn golden_box_text() {
    let (mut checked, mut diverged) = (0usize, 0usize);
    for v in common::load("box_text") {
        let text = v.a.as_deref().unwrap_or_else(|| panic!("{}: no `a`", v.id));
        let expected = v.effective();
        if v.kenro_expected.is_some() {
            diverged += 1;
        }
        let got = call(&v.func, text.as_bytes());
        if expected.get("error").is_some() {
            assert!(got.is_err(), "{}: expected an error, got {got:?}", v.id);
        } else {
            let want = expected
                .as_f64()
                .unwrap_or_else(|| panic!("{}: expected is not a number", v.id));
            let got = got
                .unwrap_or_else(|e| panic!("{}: {e}", v.id))
                .unwrap_or_else(|| panic!("{}: got NULL", v.id));
            assert_eq!(got, want, "{}: got {got}, want {want}", v.id);
        }
        checked += 1;
    }
    assert!(checked > 80, "only {checked} vectors ran");
    assert!(diverged >= 7, "only {diverged} divergence vectors ran");
}

/// The whole point of the feature: `ST_3DExtent`'s own output read back by the
/// six accessors, end to end through SQL.
#[test]
fn st_3dextent_round_trips_through_the_accessors() {
    let conn = rusqlite::Connection::open_in_memory().unwrap();
    kenro::register(&conn).unwrap();
    // 3D WKT is what kenro's ST_GeomFromText refuses by design, so the rows
    // arrive as ISO WKB through the shared reader — the way a 3D column gets
    // populated in practice.
    conn.execute("CREATE TABLE b(g BLOB)", []).unwrap();
    for wkt in ["LINESTRING Z(1 2 3,7 8 9)", "POINT Z(-4 20 100)"] {
        let wkb = common::wkt_z::to_wkb(wkt).unwrap();
        conn.execute("INSERT INTO b VALUES (?1)", [&wkb]).unwrap();
    }
    let box3d: String = conn
        .query_row("SELECT ST_3DExtent(g) FROM b", [], |r| r.get(0))
        .unwrap();
    assert_eq!(box3d, "BOX3D(-4 2 3,7 20 100)");
    let six: (f64, f64, f64, f64, f64, f64) = conn
        .query_row(
            "SELECT ST_XMin(?1), ST_YMin(?1), ST_ZMin(?1), \
                    ST_XMax(?1), ST_YMax(?1), ST_ZMax(?1)",
            [&box3d],
            |r| {
                Ok((
                    r.get(0)?,
                    r.get(1)?,
                    r.get(2)?,
                    r.get(3)?,
                    r.get(4)?,
                    r.get(5)?,
                ))
            },
        )
        .unwrap();
    assert_eq!(six, (-4.0, 2.0, 3.0, 7.0, 20.0, 100.0));
    // The aliases answer identically — they are the PostGIS spellings.
    let aliased: (f64, f64) = conn
        .query_row("SELECT ST_MinX(?1), ST_MaxY(?1)", [&box3d], |r| {
            Ok((r.get(0)?, r.get(1)?))
        })
        .unwrap();
    assert_eq!(aliased, (-4.0, 20.0));
}

/// The GeoPackage R-tree trigger path is untouched: a geometry BLOB still
/// answers, and a BLOB that is not a geometry still fails the way it did —
/// only the *TEXT rejection* went away, and what replaced it is an error that
/// still names `ST_GeomFromText`.
#[test]
fn the_blob_path_and_its_errors_are_unchanged() {
    let conn = rusqlite::Connection::open_in_memory().unwrap();
    kenro::register(&conn).unwrap();
    let x: f64 = conn
        .query_row(
            "SELECT ST_MinX(ST_GeomFromText('LINESTRING(3 4,9 1)'))",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(x, 3.0);

    let err = conn
        .query_row("SELECT ST_MinX(x'0102030405')", [], |r| r.get::<_, f64>(0))
        .unwrap_err()
        .to_string();
    assert!(err.contains("kenro"), "{err}");

    let err = conn
        .query_row("SELECT ST_MinX('LINESTRING(0 0,1 1)')", [], |r| {
            r.get::<_, f64>(0)
        })
        .unwrap_err()
        .to_string();
    assert!(err.contains("ST_GeomFromText"), "{err}");
    assert!(err.contains("BOX3D(minx miny minz"), "{err}");

    // NULL in, NULL out, as for every other function.
    let n: Option<f64> = conn
        .query_row("SELECT ST_ZMax(NULL)", [], |r| r.get(0))
        .unwrap();
    assert_eq!(n, None);
}
