//! Golden tests for the H3 functions, against vectors generated by the
//! reference H3 C library (via the python bindings; see
//! scripts/golden/h3_generate.py).

mod common;

use kenro::functions::{h3, io};
use rusqlite::Connection;

#[test]
fn golden_h3_through_pure_functions() {
    for v in common::load("h3") {
        let got: Result<serde_json::Value, kenro::Error> = (|| {
            Ok(match v.func.as_str() {
                "latlng_to_cell" => {
                    let blob = io::st_geom_from_text(v.a.as_ref().unwrap(), Some(4326))?;
                    h3::h3_latlng_to_cell(&blob, v.arg.unwrap() as i64)?.into()
                }
                "cell_to_parent" => {
                    h3::h3_cell_to_parent(v.cell.unwrap(), v.arg.unwrap() as i64)?.into()
                }
                "cell_to_string" => h3::h3_cell_to_string(v.cell.unwrap())?.into(),
                "string_to_cell" => h3::h3_string_to_cell(v.a.as_ref().unwrap())?.into(),
                other => panic!("{}: unknown fn {other}", v.id),
            })
        })();
        if v.expects_error() {
            assert!(got.is_err(), "{}: expected an error", v.id);
            continue;
        }
        assert_eq!(
            &got.unwrap_or_else(|e| panic!("{}: {e}", v.id)),
            v.effective(),
            "{}",
            v.id
        );
    }
}

#[test]
fn golden_h3_through_sql() {
    let conn = Connection::open_in_memory().unwrap();
    kenro::register(&conn).unwrap();
    for v in common::load("h3") {
        let got: rusqlite::Result<serde_json::Value> = match v.func.as_str() {
            "latlng_to_cell" => conn
                .query_row(
                    "SELECT h3_latlng_to_cell(ST_GeomFromText(?1, 4326), ?2)",
                    rusqlite::params![v.a.as_ref().unwrap(), v.arg.unwrap() as i64],
                    |r| r.get::<_, i64>(0),
                )
                .map(Into::into),
            "cell_to_parent" => conn
                .query_row(
                    "SELECT h3_cell_to_parent(?1, ?2)",
                    rusqlite::params![v.cell.unwrap(), v.arg.unwrap() as i64],
                    |r| r.get::<_, i64>(0),
                )
                .map(Into::into),
            "cell_to_string" => conn
                .query_row("SELECT h3_cell_to_string(?1)", [v.cell.unwrap()], |r| {
                    r.get::<_, String>(0)
                })
                .map(Into::into),
            "string_to_cell" => conn
                .query_row(
                    "SELECT h3_string_to_cell(?1)",
                    [v.a.as_ref().unwrap()],
                    |r| r.get::<_, i64>(0),
                )
                .map(Into::into),
            other => panic!("{}: unknown fn {other}", v.id),
        };
        if v.expects_error() {
            assert!(got.is_err(), "{}: expected an error", v.id);
            continue;
        }
        assert_eq!(
            &got.unwrap_or_else(|e| panic!("{}: {e}", v.id)),
            v.effective(),
            "{}",
            v.id
        );
    }
}
