//! Golden vectors for the two SFCGAL measurements kenro implements.
//!
//! `tests/golden/threed_sfcgal.jsonl` is generated by
//! `scripts/golden/threed_sfcgal.sql` against the reference image's
//! `postgis_sfcgal` extension (SFCGAL 1.3.8 over CGAL) — the same image every
//! other suite uses, which had been shipping the extension all along.
//!
//! Three function labels appear in the vectors and only two are kenro's:
//!
//! | label | reference call | kenro |
//! |---|---|---|
//! | `3darea` | `ST_3DArea(g)` | `ST_3DArea` |
//! | `volume` | `ST_Volume(g)` | — always 0; a surface is not a solid |
//! | `volume_solid` | `ST_Volume(ST_MakeSolid(g))` | `kenro_volume` |
//!
//! The `volume` rows are asserted *against the reference*, not against kenro:
//! they are the evidence for why `kenro_volume` is not called `ST_Volume`, and
//! a run that stopped checking them would stop noticing if the reference ever
//! changed its mind.
//!
//! Operands arrive as WKT with a Z, which kenro's `ST_GeomFromText` refuses by
//! design, so the harness builds ISO WKB with the shared `common::wkt_z`
//! reader.

mod common;

use kenro::functions::threed_solid as ts;

fn close(a: f64, b: f64) -> bool {
    (a - b).abs() <= 1e-9 * a.abs().max(b.abs()).max(1.0)
}

#[test]
fn golden_threed_sfcgal() {
    let mut checked = 0usize;
    let (mut areas, mut volumes) = (0usize, 0usize);
    for v in common::load("threed_sfcgal") {
        let wkt = v.a.as_deref().unwrap();
        let blob = common::wkt_z::to_wkb(wkt)
            .unwrap_or_else(|| panic!("{}: cannot build the operand", v.id));
        let expected = v.effective();
        match v.func.as_str() {
            "3darea" => {
                let got = ts::st_3d_area(&blob);
                if expected.get("error").is_some() {
                    assert!(got.is_err(), "{}: expected an error, got {got:?}", v.id);
                } else {
                    let want = expected.as_f64().unwrap_or_else(|| panic!("{}", v.id));
                    let got = got.unwrap_or_else(|e| panic!("{}: {e}", v.id));
                    assert!(close(got, want), "{}: got {got}, want {want}", v.id);
                }
                areas += 1;
            }
            // The reference's answer for a POLYHEDRALSURFACE or TIN. kenro has
            // no ST_Volume, so nothing of kenro's is called here — the check is
            // that the reference still answers 0, which is the whole reason
            // kenro_volume exists under its own name.
            "volume" => {
                if expected.get("error").is_none() {
                    let want = expected.as_f64().unwrap_or_else(|| panic!("{}", v.id));
                    assert_eq!(
                        want, 0.0,
                        "{}: SFCGAL's ST_Volume answered {want} for a non-SOLID — if that is \
                         real, the naming decision in docs/3d.md needs revisiting",
                        v.id
                    );
                }
            }
            // ST_Volume(ST_MakeSolid(g)) — what kenro_volume reproduces.
            "volume_solid" => {
                let got = ts::kenro_volume(&blob);
                if expected.get("error").is_some() {
                    assert!(got.is_err(), "{}: expected an error, got {got:?}", v.id);
                } else {
                    let want = expected.as_f64().unwrap_or_else(|| panic!("{}", v.id));
                    let got = got
                        .unwrap_or_else(|e| panic!("{}: {e}", v.id))
                        .unwrap_or_else(|| panic!("{}: got NULL", v.id));
                    assert!(close(got, want), "{}: got {got}, want {want}", v.id);
                }
                volumes += 1;
            }
            other => panic!("unknown fn {other} in the threed_sfcgal suite"),
        }
        checked += 1;
    }
    assert!(checked > 30, "only {checked} vectors ran");
    assert!(
        areas > 15 && volumes > 5,
        "{areas} areas, {volumes} volumes"
    );
}

/// A non-surface value has no shell, so `kenro_volume` is NULL rather than 0 —
/// the shape `ST_IsClosed` uses to say "not my kind of value". The suite's
/// `poly_2d`/`point_z` volume rows record SFCGAL answering 0 there instead,
/// which it can afford to because it has a SOLID type to distinguish them.
#[test]
fn kenro_volume_is_null_for_a_non_surface() {
    for wkt in [
        "POINT Z(1.3 2.7 3.9)",
        "POLYGON((0 0,3.4 0,3.4 2.6,0 2.6,0 0))",
        "LINESTRING Z(0 0 0,1.4 1.9 2.3)",
    ] {
        let blob = common::wkt_z::to_wkb(wkt).unwrap();
        assert_eq!(ts::kenro_volume(&blob).unwrap(), None, "{wkt}");
    }
}
