//! Golden vectors for the core-PostGIS 3D metric family.
//!
//! `tests/golden/threed.jsonl` is generated by `scripts/golden/threed.sql`
//! against the same reference image every other suite uses. Only the nine
//! functions core PostGIS has *without* SFCGAL are covered, because the
//! solid-modelling family is not in that image at all — there is nothing to
//! generate vectors from, which is the reason kenro does not implement it
//! (`tmp/3d-predicates.md`).
//!
//! The operands arrive as WKT with a Z, which kenro's `ST_GeomFromText`
//! refuses by design. So the harness builds the blob itself: it parses the WKT
//! here and emits ISO WKB, which is how a 3D geometry reaches kenro in practice
//! anyway (written by GDAL, QGIS or a CityGML importer).

mod common;

use kenro::functions::threed_metric as m3;

use common::wkt_z;

/// The ordinates of a 3D blob kenro produced, in order.
fn ordinates(blob: &[u8]) -> Vec<[f64; 3]> {
    let mut out = Vec::new();
    kenro::coords::for_each_coord(blob, &mut |c| out.push([c.x, c.y, c.z.unwrap_or(0.0)])).unwrap();
    out
}

/// PostGIS's `ST_AsEWKT` output, parsed back to ordinates for comparison.
fn expected_ordinates(ewkt: &str) -> Vec<[f64; 3]> {
    let wkb = wkt_z::to_wkb(
        &ewkt
            .replace("POINT(", "POINT Z (")
            .replace("LINESTRING(", "LINESTRING Z ("),
    )
    .unwrap_or_else(|| panic!("cannot parse expected {ewkt}"));
    ordinates(&wkb)
}

fn close(a: f64, b: f64) -> bool {
    (a - b).abs() <= 1e-9 * a.abs().max(b.abs()).max(1.0)
}

#[test]
fn golden_threed_metrics() {
    let mut checked = 0usize;
    for v in common::load("threed") {
        let a = wkt_z::to_wkb(v.a.as_deref().unwrap())
            .unwrap_or_else(|| panic!("{}: cannot build operand a", v.id));
        let b =
            v.b.as_deref()
                .map(|w| wkt_z::to_wkb(w).unwrap_or_else(|| panic!("{}: operand b", v.id)));
        // `effective()` prefers a documented-divergence override; `kenro_null`
        // is the one that cannot be spelled as a value (see common/mod.rs).
        let expected = v.effective();
        let want_null = v.kenro_null.unwrap_or(false);
        match v.func.as_str() {
            "3ddistance" | "3dmaxdistance" => {
                let got = if v.func == "3ddistance" {
                    m3::st_3d_distance(&a, b.as_ref().unwrap()).unwrap()
                } else {
                    m3::st_3d_max_distance(&a, b.as_ref().unwrap()).unwrap()
                };
                match expected.as_f64() {
                    Some(want) => {
                        let got = got.unwrap_or_else(|| panic!("{}: got NULL", v.id));
                        assert!(close(got, want), "{}: got {got}, want {want}", v.id);
                    }
                    None => assert!(expected.is_null() && got.is_none(), "{}: {got:?}", v.id),
                }
            }
            "3dintersects" => {
                let got = m3::st_3d_intersects(&a, b.as_ref().unwrap()).unwrap();
                assert_eq!(Some(got), expected.as_bool(), "{}", v.id);
            }
            "3ddwithin" | "3ddfullywithin" => {
                let d = v.arg.unwrap();
                let got = if v.func == "3ddwithin" {
                    m3::st_3d_dwithin(&a, b.as_ref().unwrap(), d).unwrap()
                } else {
                    m3::st_3d_dfully_within(&a, b.as_ref().unwrap(), d).unwrap()
                };
                assert_eq!(Some(got), expected.as_bool(), "{}", v.id);
            }
            "3dclosestpoint" | "3dshortestline" | "3dlongestline" => {
                let got = match v.func.as_str() {
                    "3dclosestpoint" => m3::st_3d_closest_point(&a, b.as_ref().unwrap()),
                    "3dshortestline" => m3::st_3d_shortest_line(&a, b.as_ref().unwrap()),
                    _ => m3::st_3d_longest_line(&a, b.as_ref().unwrap()),
                }
                .unwrap();
                if want_null {
                    assert!(got.is_none(), "{}: expected NULL, got a geometry", v.id);
                    checked += 1;
                    continue;
                }
                match expected.as_str() {
                    None => assert!(expected.is_null() && got.is_none(), "{}", v.id),
                    Some(want) => {
                        let got = got.unwrap_or_else(|| panic!("{}: got NULL", v.id));
                        let (g, w) = (ordinates(&got), expected_ordinates(want));
                        assert_eq!(g.len(), w.len(), "{}: {g:?} vs {w:?}", v.id);
                        for (gc, wc) in g.iter().zip(&w) {
                            for k in 0..3 {
                                assert!(close(gc[k], wc[k]), "{}: {g:?} vs {w:?}", v.id);
                            }
                        }
                    }
                }
            }
            "3dlineinterpolatepoint" => {
                let got = m3::st_3d_line_interpolate_point(&a, v.arg.unwrap()).unwrap();
                let (g, w) = (
                    ordinates(&got),
                    expected_ordinates(expected.as_str().unwrap()),
                );
                for (gc, wc) in g.iter().zip(&w) {
                    for k in 0..3 {
                        assert!(close(gc[k], wc[k]), "{}: {g:?} vs {w:?}", v.id);
                    }
                }
            }
            other => panic!("unknown fn {other} in the threed suite"),
        }
        checked += 1;
    }
    assert!(checked > 150, "only {checked} vectors ran");
}
